### PR TITLE
Add analytics for monzo

### PR DESCRIPTION
**Pull request by rubenwardy**
I noticed that there's already another private beta entry in the list, so I added a padlock icon for it and added my own

### CODE REVIEW

**Comment by rdingwall** [comment]
Hey @rubenwardy, thanks for the contribution but all 3rd-party API integrations are private at the moment, at least until we resume API development (after the current account launch). If it's okay, I'll close this for now.

**Comment by rubenwardy** [comment]
Why is ~~Monies~~ Quidss App there then?

EDIT: Quids

**Comment by rdingwall** [comment]
Sorry my mistake - I meant yes to adding private beta integrations, but we don't really need padlock status icons because everything should technically have a padlock right now. Would you mind updating your PR and I'll merge?

**Comment by rubenwardy** [comment]
that padlock means that it's closed source - all the others you can download and add your API key to

but I don't mind removing that

**Comment by rdingwall** [comment]
I think it would be simpler if it was just a list of links :)

**Comment by AlexIsMaking** [comment]
I agree with Richard.

And also, the creator of the app should make it clear that the app is closed source in their repository's read me.

You could add a key for this repository's list explaining what the padlock icon means but it seems like there's a good chance that an app could switch from open to close or vice versa & the app developer would forget to update this repository too.

**Comment by rdingwall** [comment]
thanks @rubenwardy !

**Pull request merged**
